# https://taskfile.dev

version: '3'

vars:
  # GREETING: Hello, World!
  # WORKDIR: $PWD

tasks:
  profile-build:
    cmds:
      - nix build .#devEnv --out-link .nix-env
    sources:
      - flake.nix
      - flake.lock
      - poetry.lock
      - pyproject.toml
    generates:
      - .nix-env

# --exclude ".git/**"
