# https://taskfile.dev

version: "3"

vars:
  PROFILE_FOLDER: .nix-env
# GREETING: Hello, World!
# WORKDIR: $PWD

tasks:
  profile-build:
    cmds:
      - rm -rf {{.PROFILE_FOLDER}}
      - nix build .#devEnv --out-link {{.PROFILE_FOLDER}}
    sources:
      - flake.nix
      - flake.lock
      - poetry.lock
      - pyproject.toml
    generates:
      - "{{.PROFILE_FOLDER}}"
# --exclude ".git/**"
